### PR TITLE
Add Configuration.Taml.Net

### LINKED ISSUE #63: Need Configuration package for .NET 5+
Let's build `Microsoft.Extensions.Configuration.TAML` but it needs to be in our own namespace

### PR DESCRIPTION
**Pull request by Kahbazi**
Fixes https://github.com/csharpfritz/TAML/issues/63

### CODE REVIEW

**Comment by csharpfritz** [comment]
Thank you so much for putting this together so quickly!  I noticed that the folder and project name is not spelled correctly:  **Configuration.Taml.NET**

I'll review more of the code

**Comment by csharpfritz** [comment]
I don't think we should reference the Taml.NET project directly, but rather go through a NuGet package reference so that consumers get that NuGet package installed as well.

**Comment by csharpfritz** [comment]
I like the inline TAML in the tests!

**Comment by Kahbazi** [comment]
> but rather go through a NuGet package reference so that consumers get that NuGet package installed as well.

This shouldn't be necessary. By referencing the nuget package `Configuration.Taml.Net` will always be one package behind. Also `dotnet pack` would detect that `TAML.NET` is a package and add that to the dependencies of `Configuration.Taml.Net`.

**Comment by csharpfritz** [comment]
I'm going to review and merge this in today's stream.   We'll add a GitHub action to publish a NuGet package as well. HUGE thanks for the contribution!

**Pull request merged**
